### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by AtomicNibble** [FileGo/octopusenergyapi#1]
Hello thought would post comments, feel free to close issue yourself.

When returning errors with format strings the error package you use has a `errors.Errorf` function. https://godoc.org/github.com/pkg/errors#Errorf (is only the default error package that don't have ErrorF) so don't have to use the fmt package.

Also the error package you use (github.com/pkg/errors) adds callstack info to errors, so it's better to only use functions from this package instead mix & match then if you add some generic error handler later all errors will have stacks.

And just a style thing when returning a error I normally just return nil for the type so:

```go
return []Consumption{}, fmt.Errorf("http get error: %w", err)
```

becomes 
```go
return nil, fmt.Errorf("http get error: %w", err)
```
but again just personal preference 😄 

Rest looks fine, maybe only compile the postcode regex string once though in `func init() {}`

Cool package might use myself. 👍

**Comment by FileGo** [comment]
Thanks for leaving the feedback, it is highly appreciated.

I've made some changes and merged into main.
